cluster:
  zookeeper:
    hostPort: localhost:2181
    sessionTimeout: 100000
agent_server:
  jetty:
    host: 0.0.0.0
    port: 10800
    context_path: /
agent_stream:
  grpc:
    host: 192.168.10.13
    port: 11800
  jetty:
    host: 0.0.0.0
    port: 12800
    context_path: /
ui:
  jetty:
    host: 0.0.0.0
    port: 12800
    context_path: /
collector_inside:
  grpc:
    host: 127.0.0.1
    port: 11800
#storage:
#  elasticsearch:
#    cluster_name: CollectorDBCluster
#    cluster_transport_sniffer: true
#    cluster_nodes: localhost:9300
#    index_shards_number: 2
#    index_replicas_number: 0
storage:
    h2:
      url: jdbc:h2:~/collector
      user_name: sa
      password: sa